// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvpeknlczknywtapbcsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cGVrbmxjemtueXd0YXBiY3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2OTk4MzYsImV4cCI6MjA1MDI3NTgzNn0.9vCVlKAZXgOPoxxjNAwMY8qC5Jjcj49zXQPVHJkzksM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);